[package]
name = "gc-adapter-neo"
version = "1.1.1"
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>, Álex Román Núñez <eirexe@eirteam.moe>"]
edition = "2018"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/gc-adapter"
repository = "https://github.com/EIRTeam/gc-adapter"
description = "A Rust library for working with the Nintendo Gamecube Controller Adapter"

[package.metadata.docs.rs]
all-features = true

[dependencies]
binread = "1.4"
modular-bitfield = "0.11.2"

rusb = { version = "0.9.4", optional = true }

[features]
libusb = ["rusb"]
